### ISSUE TITLE
Miss typescript defination for setAttr function

### ISSUE THREAD

**Issue by hdsuperman** [ProseMirror/prosemirror-tables#124]
https://github.com/ProseMirror/prosemirror-tables/blob/89b87d8155ee445cad15381640af964c82488d13/src/index.js#L69
setAttr function has been exported in index.js file, but miss defination in index.d.ts file

add setAttr defination 

```typescript
export function setAttr(attrs: any, name: string, value: any): any;
```
to here: 

https://github.com/ProseMirror/prosemirror-tables/blob/89b87d8155ee445cad15381640af964c82488d13/index.d.ts#L306

**Comment by ocavue** [comment]
Fixed in v1.3.0-beta.1
