### ISSUE TITLE
undo column re-sizing with cmd+z

### ISSUE THREAD

**Issue by eshvedai** [ProseMirror/prosemirror-tables#13]
**Browser**
Chrome

**Expected Behavior**
When I resize a column and then press Cmd+Z, it should undo my changes.

**Actual Behavior**
Cmd+Z does not undo resizing of a column. It does work only if a new column is created before resizing.

**Comment by marijnh** [comment]
This is working for me. Could you provide a bit more details on how you are testing it?

**Comment by eshvedai** [comment]
I figured it out, it doesn't work if I open the demo page and start resizing right away without making the editor in focus (history is working as I'm able to undo/redo using toolbar keys). If I put the cursor inside of the editor making it focused, keyboard shortcuts start working. Lets ignore this, I'm sure its  not very common.
