### ISSUE TITLE
Resizing columns sometimes changes the previous column

### ISSUE THREAD

**Issue by oodavid** [ProseMirror/prosemirror-tables#132]
If you drag a cell border, occasionally the previous border is resized.

![Table Resizing](https://user-images.githubusercontent.com/46879/106267414-8208f500-6221-11eb-8ab2-eeb4d300a1a6.gif)

From first-glance it looks like it selects the previous border when hovering over the **middle-pixel** in the table border.

**Comment by mattcasey** [comment]
I think this issue would be fixed by this PR https://github.com/ProseMirror/prosemirror-tables/pull/99

**Comment by oodavid** [comment]
I believe this was fixed with #199 - I can't replicate, assuming it's fixed
