### ISSUE TITLE
Wondering why TableView class is not properly exposed

### ISSUE THREAD

**Issue by linsannety** [ProseMirror/prosemirror-tables#133]
context: I would like to wrap the tableWrapper in an outer wrapper for styling purposes.

I figured maybe I could take TableView and do some updating to its constructor, however it's not included in the type files and maybe I'm approaching this incorrectly. Is it safe to use as is (there's the risk that TableView's implementation will be updated in a future and our code could break), would you consider exposing it?

For reference, this is how I tried to extend the class in ts

```
class TableView extends (ProsemirrorTables as any).TableView {
    constructor(node: ProsemirrorModel.Node, cellMinWidth: number) {
        super(node, cellMinWidth);

        const wrapper = document.createElement("div");
        wrapper.className = "ProsemirrorEditor-outerTableWrapper";
        wrapper.appendChild(this.dom);
        this.dom = wrapper;
    }

**Comment by ocavue** [comment]
Fixed in v1.3.0-beta.1
