### ISSUE TITLE
typescript definitions for CellSelection do not extend Selection

### ISSUE THREAD

**Issue by jessica-branchizio** [ProseMirror/prosemirror-tables#134]
I was running into an issue in which Typescript would not allow me to pass something of type `CellSelection` into a function that accepted `Selection` as a parameter.
Looking over the code inside of `node_modules` I see that in `cellselection.js`, `CellSelection` extends `Selection`:
```
export class CellSelection extends Selection {
```
However, in the `index.d.ts` file, `CellSelection` does not extend `Selection`:
```
export class CellSelection<S extends Schema = any> {
```
This issue is fixed by #126 and it would be super helpful to get this merged in. If there's anything I can do to help out let me know!

**Comment by ocavue** [comment]
Fixed in v1.3.0-beta.1
