### ISSUE TITLE
Column resize handle appears in the wrong place

### ISSUE THREAD

**Issue by eshvedai** [ProseMirror/prosemirror-tables#14]
**Browser**
Firefox 54

![ff-resize-handle](https://user-images.githubusercontent.com/26512812/31255279-d38b1cd8-aa77-11e7-8337-2cf566513616.gif)

**Comment by marijnh** [comment]
Going by your screencast, I opened the demo, added a column after the cell containing 'One', and then dragged the column border on the left of that new column. But I'm not seeing the problem occur (also using Firefox). Are you doing anything that's not easily seen in the screencast?

**Comment by eshvedai** [comment]
This time I just opened the demo page and hovered over the first handle, it requires a bit of cursor movement by 1-2 pixels back and forth over the cell border to catch this. 

If the handle is under the cursor, resizing works correctly. If it jumps to the right border of the next cell, I'm able to resize the next cell instead.

![ff-drag-handle](https://user-images.githubusercontent.com/26512812/31303222-9e48062e-ab55-11e7-8e09-601782637370.gif)

**Comment by marijnh** [comment]
Odd. I've been moving the mouse over the cell border, in that exact Firefox version on that exact platform, for five minutes, but haven't been able to reproduce the issue. Looking at the code (in `handleMouseMove`) I also can't spot anything that would lead to this behavior. One possibility is that `view.posAtCoords` in `edgeCell` returns an inaccurate result on your platform for some reason. But that's hard to debug if I can't observe it.

**Comment by eshvedai** [comment]
you're right, seems like when I move the cursor from right to left over the handle, it jumps to the right when the `target` from `handleMouseMove` is cell "One" td DOM node, whereas `posFromCaret` -> `desc.dom` is still cell "Two", which means `edgeCell` `side` attribute becomes `right` when I still have an old `$cell`. I'll try to figure out how to fix it :)

**Comment by marijnh** [comment]
One interesting piece of information would be what `caretPositionFromPoint` returns on your browser for the problematic coordinates. That's what `posAtCoords` is likely basing its result on, and if it's returning something strange, we'll have to somehow find a way to notice when this happens and correct it.

**Comment by eshvedai** [comment]
Its working fine with Firefox 57, closing this until someone else will complain about having the same issue.
