### ISSUE TITLE
Table horizontal scroll after resizing a column

### ISSUE THREAD

**Issue by eshvedai** [ProseMirror/prosemirror-tables#15]
**Browser**
Chrome

**Expected behavior**
If the table is smaller than the viewport width or the table container, then the table should scroll horizontally
![table-resizing-demo](https://user-images.githubusercontent.com/26512812/31255538-1c53d90e-aa79-11e7-9ec1-ef261dcc3043.gif)

**Actual behavior**
last column gets broken after resizing if preceding column has fixed width.
![resize_scroll](https://user-images.githubusercontent.com/26512812/31255347-28196ab6-aa78-11e7-8364-425be4d6d7b6.gif)

**Comment by marijnh** [comment]
> last column gets broken after resizing if preceding column has fixed width.

It's not broken, it's just narrow because it doesn't have a fixed width and is thus resized down to the minimum cell width, which is 25 pixels by default but which you can configure when creating the column resizing plugin.

**Comment by eshvedai** [comment]
oh, you're right, sorry.
