### ISSUE TITLE
Index.d.ts does not have setAttr,  pointAtCell and TableView which are present in Index.js (prosemirror-tables)

### ISSUE THREAD

**Issue by denilbaicil** [ProseMirror/prosemirror-tables#164]
Reason seems to be that [DefinitelyTyped](https://github.com/ProseMirror/prosemirror-tables/blob/89b87d8155ee445cad15381640af964c82488d13/index.d.ts) doesn't export all those available in [index.js](https://github.com/ProseMirror/prosemirror-tables/blob/89b87d8155ee445cad15381640af964c82488d13/src/index.js).

Issues faced in TypeScript:
```
error TS2305: Module '"prosemirror-tables"' has no exported member 'pointsAtCell'.
error TS2305: Module '"prosemirror-tables"' has no exported member 'setAttr'.
error TS2305: Module '"prosemirror-tables"' has no exported member 'TableView'.

```

**Comment by ocavue** [comment]
Fixed in v1.3.0-beta.1
