### ISSUE TITLE
native handlebars in firefox

### ISSUE THREAD

**Issue by johanneswilm** [ProseMirror/prosemirror-tables#22]
I am running prosemirror-tables and in Firefox I see the native resize controls. In CK Editor they turn them off:

See here https://github.com/ckeditor/ckeditor-dev/blob/fc149eeb4b92ba9ea64c6becee9e0ddff906097f/plugins/wysiwygarea/plugin.js#L554-L558

I also see you turn them off in the demo:

https://github.com/ProseMirror/prosemirror-tables/blob/634a70178bc52bad3caf030ded1e96944815724d/demo.js#L64-L65

Any reason this cannot be made part of the general plugin?

**Comment by marijnh** [comment]
See https://github.com/ProseMirror/prosemirror/issues/432. A pull request to mention this in the docs for this module would be nice, but I don't think adding global side effects on load time is a good idea for a library.
