### ISSUE TITLE
press enter in table cell will create new row。

### ISSUE THREAD

**Issue by ximing** [ProseMirror/prosemirror-tables#23]
1，clone prosemirror-tables
2，run demo

See the gif for details
![10 -11-2017 11-21-28](https://user-images.githubusercontent.com/4659887/31420910-e9356576-ae09-11e7-855c-c93c4f9bf9da.gif)

**Comment by marijnh** [comment]
It doesn't, for me. Which browser are you using?

**Comment by marijnh** [comment]
Oh, hold on, I did manage to reproduce. Attached patch should address this.
