### ISSUE TITLE
When you press the Delete key below the table，will create new table row

### ISSUE THREAD

**Issue by ximing** [ProseMirror/prosemirror-tables#24]
1，clone ProseMirror/prosemirror-tables
2，run demo
3，Move the cursor to the bottom of the table
4，press the delete key

![delete under table](https://user-images.githubusercontent.com/4659887/31529593-d2b0b386-af9f-11e7-8fd0-7caa8b341c57.gif)

mac system，
browser is safari and chrome

**Comment by marijnh** [comment]
When I press delete in that situation, nothing happens. But I did see the outcome your screencast shows when pressing backspace. Attached patch helps with that. Does it solve your problem?

**Comment by ximing** [comment]
yeah,I close this.
