### ISSUE TITLE
RangeError: Duplicate use of selection JSON ID cell

### ISSUE THREAD

**Issue by rohitt-gupta** [ProseMirror/prosemirror-tables#257]
I have been trying to work on prosemirror-tables.
Requirements are simple, clone paper's table component([https://dropbox.com/paper](https://t.co/hwJJ2Ww6IR or notion table))

Essentially, when you click inside the table the buttons get active, and when you click outside it gets removed. and the column drag to create new table columns. (if anyone have any example on this please share)

As I did with all my other components, I have build all my node views manually by forking prosemirror and then customizing them.

but when I am not able to fork tableEditing() plugin.
When I fork each and everything from the prosemirror-tables to my codebase, it gives me an error known as 

|- **RangeError: Duplicate use of selection JSON ID cell** (screenshot attached)
<img width="1796" alt="Screenshot 2024-12-01 at 9 37 42 PM" src="https://github.com/user-attachments/assets/0b421796-2a5d-4981-967f-8da46f99f22a">

Do you have any suggestions on how can I proceed?

This is what I am doing right now if it helps
![image](https://github.com/user-attachments/assets/53f260d3-edce-4273-9a7d-101d86a09d99)

Here is the **gist** for the tableEditing file I have created:
https://gist.github.com/rohitt-gupta/253ab1d0a654bee1da53cfb339c99a27

**Comment by ocavue** [comment]
In ProseMirror, every kind of Selection must have a globally unique id. For example, the `CellSelection` class registers itself with the name `"cell"` ([source code](https://github.com/ProseMirror/prosemirror-tables/blob/240cb67a981f8ff0af1d8995334afbbfe08845d9/src/cellselection.ts#L354)).

To avoid this issue, you need to make sure you only have one `"cell"` selection in your codebase. If you are forking `prosemirror-tables`, makes sure that you only get one copy of `prosemirror-tables` (i.e. don't install `prosemirror-tables` in your `node_modules`).
