### ISSUE TITLE
TableView TypeScript error with prosemirror-view@1.37.0 and newer

### ISSUE THREAD

**Issue by raymondcao-everlaw** [ProseMirror/prosemirror-tables#258]
The `NodeView` interface imported from `prosemirror-view` in [`tableview.ts`](https://github.com/ProseMirror/prosemirror-tables/blob/master/src/tableview.ts) was changed in version 1.37.0 (https://github.com/ProseMirror/prosemirror-view/commit/cebd804782228f235aa972ea204b22045bde2132) to accept a `ViewMutationRecord` instead of a `MutationRecord` for `ignoreMutation`.

Since this package has not yet been updated to support this change, my project has been getting the following TypeScript type error (with [`strict` option](https://www.typescriptlang.org/tsconfig/#strict) enabled):

```
node_modules/prosemirror-tables/dist/index.d.ts(558,5): error TS2416: Property 'ignoreMutation' in type 'TableView' is not assignable to the same property in base type 'NodeView'.
  Type '(record: MutationRecord) => boolean' is not assignable to type '(mutation: ViewMutationRecord) => boolean'.
    Types of parameters 'record' and 'mutation' are incompatible.
      Type 'ViewMutationRecord' is not assignable to type 'MutationRecord'.
        Type '{ type: "selection"; target: Node; }' is missing the following properties from type 'MutationRecord': addedNodes, attributeName, attributeNamespace, nextSibling, and 3 more.
```

My project has `prosemirror-view@1.37.1` and `prosemirror-tables@1.6.1` installed.

I believe the fix for this would include:
- Updating the method type signature for `ignoreMutation` in `TableView` to accept a `ViewMutationRecord` instead of a `MutationRecord`.
- Updating `prosemirror-view` dependency version to `1.37.0` in `package.json`.

**Comment by ocavue** [comment]
Thanks. Fixed in v1.6.2
