### ISSUE TITLE
Add createTable command?

### ISSUE THREAD

**Issue by hubgit** [ProseMirror/prosemirror-tables#26]
Would it make sense to add `createTable` to [the commands](https://github.com/ProseMirror/prosemirror-tables/blob/master/src/commands.js), similiar to [the previous `createTable` command in `prosemirror-schema-table`](https://github.com/ProseMirror/prosemirror-schema-table/blob/master/src/schema-table.js#L65)?

**Comment by eshvedai** [comment]
please check https://github.com/atlassian/prosemirror-utils/blob/master/src/table.js, there is a number of useful methods for tables
