### ISSUE TITLE
Copy-pasting tables from external source doesn't work in IE 11/Edge

### ISSUE THREAD

**Issue by eshvedai** [ProseMirror/prosemirror-tables#3]
When I copy and paste table from external html page in IE 11/ Edge, each row of the original table becomes a paragraph when pasted.

**Comment by marijnh** [comment]
Is this still happening with 0.22/0.23? I tried to reproduce it in Edge but didn't see the problem occur.

**Comment by eshvedai** [comment]
I'll try again when we bump PM to the latest version

**Comment by eshvedai** [comment]
I can still reproduce it on version 1.0.0. I copied cells from our Editor in Chrome and pasted it in Edge (using https://www.browserstack.com)

![paste-cells](https://user-images.githubusercontent.com/26512812/34546975-e03abd24-f14b-11e7-862b-b5592be3f508.gif)

**Comment by marijnh** [comment]
Can you point me at some static HTML page which contains tables that, when copied into ProseMirror, show the issue? (Also please tell me exactly what you selected, and how, when copying.)

**Comment by eshvedai** [comment]
| aaa       | bbb | ccc    |
| ------- |:----:| -----:|
| one      | two  | three |

Select any two cells from the table above and paste it into ProseMirror editor. In my example I selected two header cells (aaa, bbb):
<img width="188" alt="screen shot 2018-01-05 at 10 20 31 am" src="https://user-images.githubusercontent.com/26512812/34588625-16c0a0f0-f202-11e7-9c25-a1808f97dc72.png">


This is what gets pasted:
```
<meta charset='utf-8'><table style="box-sizing: border-box; border-spacing: 0px; border-collapse: collapse; margin-top: 0px !important; margin-bottom: 0px !important; display: block; width: 672px; overflow: auto; color: rgb(36, 41, 46); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><thead style="box-sizing: border-box;"><tr style="box-sizing: border-box; background-color: rgb(255, 255, 255); border-top: 1px solid rgb(198, 203, 209);"><th style="box-sizing: border-box; padding: 6px 13px; font-weight: 600; border: 1px solid rgb(223, 226, 229);">aaa</th><th align="center" style="box-sizing: border-box; padding: 6px 13px; font-weight: 600; border: 1px solid rgb(223, 226, 229);">bbb</th></tr></thead></table>
```
Result:
* Edge 16: 
<img width="499" alt="screen shot 2018-01-05 at 10 17 57 am" src="https://user-images.githubusercontent.com/26512812/34588566-c785914e-f201-11e7-9ea6-80dd3ff0c850.png">
* Chrome:
<img width="195" alt="screen shot 2018-01-05 at 10 18 54 am" src="https://user-images.githubusercontent.com/26512812/34588581-e38be5aa-f201-11e7-87c7-ace111db684a.png">

**Comment by marijnh** [comment]
In Edge 16.16257, I'm seeing the same behavior as Chrome (and Firefox) — the first cell ends up as a paragraph, the second as a table. That's not great, and I'm looking into it, but I haven't been able to get the behavior where it's all flattened into a paragraph.

**Comment by marijnh** [comment]
Attached patch (which you get by using prosemirror-model 1.1.0 and prosemirror-view 1.07) should help with the unnecessary opening of the first table cell.

**Comment by eshvedai** [comment]
Thanks! I think its possible that the Edge bug is related to browserstack testing which is not the same as testing in a native browser, closing the issue.
