### ISSUE TITLE
There's code that accidentally ended up in 0.7.0

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror-tables#47]
I clumsily committed some changes that I had meant to drop in 27b8bc15, and they break deleting table selections. Apologies! I've reverted them in e180a2bf151c7a5b81831fbc1df43e1dd7380f9d, and would appreciate if you could tag a 0.7.1 with that patch!

**Comment by eshvedai** [comment]
Thanks for the fix, released in `0.7.1`.
