### ISSUE TITLE
Strange selection issue when clicking to select all text in a cell

### ISSUE THREAD

**Issue by nathf** [ProseMirror/prosemirror-tables#60]
This issue seems related to https://github.com/ProseMirror/prosemirror-tables/issues/1 with a slightly different means of selection

Given this scenario, the space in the text selected seems important (https://kmmx3y7nl5.codesandbox.io/):
![cell-deletion](https://user-images.githubusercontent.com/646098/45069405-978c9a00-b10f-11e8-9d9f-b10e98c27170.gif)

Chromes (/ Safari) selection seems to cross into the next cell when clicking to select all text in a cell and upon hitting backspace deletes the whole cell instead of its contents.

Some selection normalising is already happening here:
https://github.com/ProseMirror/prosemirror-tables/blob/ef012d75ea3e8af50821eb9d8be99d787c33ef38/src/cellselection.js#L252-L271

@marijnh would it be best to add some more normalising for a TextSelection that crosses tableCell boundaries? Selecting contents across multiple cells should result in a cell selection so hopefully shouldn't affect that scenario.

**Comment by marijnh** [comment]
> when clicking to select all text in a cell 

What kind of clicking are you doing? When I triple-click the cell, I get a cell selection, and backspacing deletes just the cell's content.

**Comment by nathf** [comment]
@marijnh If you double click the second `Two`, followed by a single click. That should select both words. I can't consistently select it but about 2 out 3 times.

**Comment by marijnh** [comment]
You mean a shift-click at the start of the first `Two`, when you say single click? I tried that a bunch of times in Chrome 68, but don't get the behavior you describe, even after 10 tries.

**Comment by nathf** [comment]
I've added a button to the sandbox that creates the odd selection programmatically. If you hit the button (Set selection) then hit backspace you should get the behaviour

**Comment by marijnh** [comment]
Right, at that point the selection seems to be a text selection starting in one cell and ending at the start of the next cell. For such a selection, the behavior we're getting is appropriate I guess. So the issue would be why that selection is created for this interaction, and that I still can't test.

If you create a raw (non-prosemirror) editable table and perform the same mouse actions, what are the start and end points of the DOM selection? The question is whether ProseMirror is doing something weird (in which case we should fix it) or whether you browser is giving it a weird selection (in which case the solution would be to recognize such situations and normalize the resulting selection).

**Comment by nathf** [comment]
It gives the same points (sandbox: https://kmmx3y7nl5.codesandbox.io/vanilla.html)

I also re-created the gif with mouse button press turned on (Chrome Version 68.0.3440.106), hopefully this is more helpful
![click-selection](https://user-images.githubusercontent.com/646098/45092515-004c3480-b159-11e8-86ee-827f25b058b0.gif)

**Comment by marijnh** [comment]
Wait, so you _did_ triple click after all?

In the current demo, triple-clicking no longer creates a cell selection for some reason. So then the approach would be to look at `handleTripleClick` in prosemirror-tables/src/input.js and see why it isn't taking effect.

**Comment by nathf** [comment]
I added logs in the `handleDoubleClick` and `handleTripleClick`

It looks like it fires doubleClick twice to get that selection (even though theres three clicks), it never gets into the `handleTripleClick`
![tripleclick-doubleclick](https://user-images.githubusercontent.com/646098/45128452-72f0fa80-b1c1-11e8-80ba-6523f69cfe5d.gif)

**Comment by marijnh** [comment]
Hm, that might be a bug in the view code—looking at it, it does indeed seem possible that it reported some triple clicks, depending on the timing, as two double clicks. Could you try if the patch I've attached fixes this for you?

**Comment by nathf** [comment]
Thanks for the patch @marijnh, that fixes the triple click handling.

Through testing this patch I found another way to still get this selection (triple click on a word, followed by a single click):
![after-selection-2](https://user-images.githubusercontent.com/646098/45192969-0c3a1280-b28f-11e8-984b-aaa686ab5e04.gif)

The tableCell that is being removed also has `isolating: true` defined, when hitting backspace (or other regular editing actions) it shouldn't cross into the next cell/node should it?

**Comment by marijnh** [comment]
> The tableCell that is being removed also has isolating: true defined, when hitting backspace (or other regular editing actions) it shouldn't cross into the next cell/node should it?

No, that's not what `isolating` does—it contains editing actions that happen inside the node, but if the selection already crosses the node boundary, deleting it will delete all the selected content.

> we could normalise the selection if its a TextSelection across cells?

You could, but I do think selecting across cells is sometimes useful. It is definitely bad if you can't drag-select across a table to select the whole thing (plus other content around it). Maybe something more conservative that only normalizes selections that start in a cell and end at the start of the next cell or end of the previous cell.

**Comment by nathf** [comment]
Thanks for your help and patience on this @marijnh, i'll give that normalising a go.
