### ISSUE TITLE
Making TableView public

### ISSUE THREAD

**Issue by dddotsev** [ProseMirror/prosemirror-tables#63]
Would it be possible to export the TableView class from the module? It would be very nice to be able to extend that reuse the logic. My use case, or at least one of them, is that we need to add attributes to the table element and that's currently not possible since the current TableView doesn't do that.

I could create the PR if you say that's OK.

**Comment by eshvedai** [comment]
`TableView` class is just an example of possible nodeView implementation for tables, that's why its so simple. In real applications you'd want much more than that. I'd recommend creating your own nodeView and re-using `updateColumns` which has been exported.
