### ISSUE TITLE
Drag and drop of table content is blocked

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror-tables#8]
Patch ee18e58ee prevents the effect of dropping content whose HTML matches `"<table>"`. I'd be interested in what the reason for that is, but I don't think it is a good idea — dragging content with tables seems like a valid thing for a user to do.

**Comment by eshvedai** [comment]
it happens quite often when you try to select a few cells, but end up dragging the content of a cell instead. Then, by dropping the content it created a new column in the end of the table. I decided to disable drag'n'drop until we find a proper solution. Let's revert that fix, we can disable that on our side I think.

**Comment by marijnh** [comment]
Have you been able to find the precise circumstances that lead to this problem? I haven't seen it happen before. Does it occur on all browsers or just some?

**Comment by eshvedai** [comment]
- I have a cell selection and I want to extend my selection to span a few more cells. 
- I click on a cell and drag it, it creates a new (4th) column. 
- When I do Cmd+Z to undo it, I still have 4 columns.

I'd say its an edge case and not quite common behavior, its up to you. (I reverted my patch).

![drag-undo](https://user-images.githubusercontent.com/26512812/31256197-b4c68a6c-aa7c-11e7-8a70-518aec16de32.gif)

**Comment by marijnh** [comment]
PR #16 addresses the failure of undo in this case.

In general, starting a drag on the selection is interpreted as dragging, rather than extending, that selection. I think it's useful to support that here as well. I did notice that the cell selection mouse handling code gets confused after dragging (it thinks the user is selection), which I'll submit another PR for.
